Changed some hardcoded value to properties
congruiyS2023/platemate-web pull request #6
Opened 2023-12-02 11:00 UTC by hanqidS2023

![Screenshot 2023-12-02 at 3 00 16 AM](https://github.com/congruiyS2023/platemate-web/assets/123215156/7908ab76-6ef5-4a59-bb1d-acc44710ce67)

2023-12-02 20:18 UTC, xyang6230 commented on src/components/RedistributeCard.jsx
1. weight can be part of props
2. another onClickCard action would need to be passed in as a param
3. need to support image in this card (probably add as props.image)

2023-12-03 00:57 UTC, hanqidS2023 commented
![Screenshot 2023-12-02 at 4 56 54 PM](https://github.com/congruiyS2023/platemate-web/assets/123215156/4e81cd38-1d00-4f59-a067-d934d85d259e)

2023-12-03 04:28 UTC, congruiyS2023 requested changes
Looking good! Except for duplicate tailwind decorations on font color.

2023-12-03 04:28 UTC, congruiyS2023 commented on src/components/RedistributeCard.jsx
>          <p className="text-xs text-black text-primary font-paragraph">
`text-black` applies the same CSS property as `text-primary`, please only preserve one

2023-12-03 04:28 UTC, congruiyS2023 commented on src/components/RedistributeCard.jsx
>          <p className="text-xs text-black text-primary">
Same here, preserve one decoration to font color.

2023-12-03 04:29 UTC, congruiyS2023 commented on src/components/RedistributeCard.jsx
>          <p className="text-xs text-black text-primary">
Also on line 43 and line 46,  choose one between `text-primary` and `text-white`.

2023-12-03 05:22 UTC, congruiyS2023 approved these changes
Great!

2023-12-03 05:22 UTC, merged