add chat page
congruiyS2023/platemate-web pull request #7
Opened 2023-12-03 03:10 UTC by ziyangcS2023

2023-12-03 03:17 UTC, ziyangcS2023 commented
chatting feature done

2023-12-03 04:22 UTC, congruiyS2023 requested changes
After click on the send button, my text input in not cleared, neither do I see my sent message on screen.

2023-12-03 04:22 UTC, congruiyS2023 commented on src/pages/chat.jsx
> +            <Input
Please use [`CustomInputWithSubmit`](https://github.com/congruiyS2023/platemate-web/blob/54da89ae5b2ef00b4ced187d4aeb087837acaacb/src/components/CustomInputs.jsx#L34) here.

2023-12-03 07:07 UTC, ziyangcS2023 commented on src/pages/chat.jsx
> +            <Input
resolved in [78f1128](https://github.com/congruiyS2023/platemate-web/pull/7/commits/78f11287f98a26d5d9946513ac052e731bb4e512)

2023-12-03 19:47 UTC, congruiyS2023 requested changes
Great!! Now just change the style of ChatMessage to match the style guide then I think you can begin to incorporate this page to @YinzhuSU 's user flow.
<img width="358" alt="Chat" src="https://github.com/congruiyS2023/platemate-web/assets/120247054/808b5c06-0fa4-468f-b5d6-476cf0ead9d9">

2023-12-03 23:06 UTC, yinzhusS2023 commented
indeed!

2023-12-04 06:25 UTC, ziyangcS2023 commented
fixed stylings on [3f39b03](https://github.com/congruiyS2023/platemate-web/pull/7/commits/3f39b036ce548901d9d593162c9b3148f507959a)

2023-12-04 06:59 UTC, congruiyS2023 commented
Lgtm! @YinzhuSU Please incorporate the route name!

2023-12-04 17:09 UTC, yinzhusS2023 commented
Hi @congruiyS2023 

I checked the PR, it looks good.
I also resolved the conflict to the master branch. Would you please resolve your Change request and merge it to master?
Thanks!

2023-12-04 17:11 UTC, yinzhusS2023 approved these changes
Nice work!
Next time before you push your code to remote, remember to pull the latest code from master, merge the master to your feature branch and resolve any conflicts, then push and make the PR.

2023-12-04 18:11 UTC, congruiyS2023 requested changes

2023-12-04 18:11 UTC, congruiyS2023 commented on src/App.js
> +              <Route path="/chat" element={<Chat />} />
@ziyangcS2023 @YinzhuSU Please change the path to `/recycle/chat` to match the change in route names, thanks!

2023-12-04 18:35 UTC, congruiyS2023 approved these changes
Nice work guys!

2023-12-04 18:35 UTC, congruiyS2023 commented on src/App.js
> +              <Route path="/recycle/chat-with-recycle-companies" element={<Chat />} />
If we are really aiming for full REST, the path should be `recycle/chat/:recycleCompanyId`, but I think we're good here. Nice work guys!

2023-12-04 18:36 UTC, congruiyS2023 commented on src/App.js
> +              <Route path="/recycle/chat-with-recycle-companies" element={<Chat />} />
@ziyangcS2023 @YinzhuSU Just FYI ⬆️ I'm resolving it rn.

2023-12-04 18:37 UTC, merged